name: Deploy-Dev
on:
  push:
    branches:
      - develop
#  pull_request:
#    branches:
#      - develop
#    types: [closed]
jobs:
  inject-source:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: Develop
    steps:
      - name: execute commands via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_MACHINE }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWD }}
          port: ${{ secrets.PORT }}
          script: cd /srv/be-api && git checkout develop && git pull || git clone https://github.com/coclabs/be-api.git
